In [4]:
import numpy as np
np.asanyarray([[[1,2],[5,6],[7,8]]])


array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [6]:
mat=np.matrix([[1,2],[3,4]])

mat

matrix([[1, 2],
        [3, 4]])

In [7]:
np.asanyarray(mat) #still will be matrix

matrix([[1, 2],
        [3, 4]])

In [8]:
np.asarray(mat) #remove any to become as array

array([[1, 2],
       [3, 4]])

In [9]:
a=5
np.array(a)

array(5)

In [10]:
t=([1,2,3],[4,5,6])
type(t)

tuple

In [11]:
l=[1,2,3,4,5]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [12]:
arr[0]

1

In [13]:
a=arr
a

array([1, 2, 3, 4, 5])

In [16]:
arr[0]=1000  #we changed 0 position 
arr

array([1000,    2,    3,    4,    5])

In [18]:
a   #we only changed arr position but also changed in a


array([1000,    2,    3,    4,    5])

In [20]:
#to generate an array
np.fromfunction(lambda i,j :i==j,shape=(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [23]:
arr.shape #dimention (it is 1d)

(5,)

In [24]:
arr.size #the no.of elements

5

In [26]:
np.fromfunction(lambda i,j :i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [27]:
iterable=(i*i for i in range(5))
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [28]:
np.fromstring('23 34 67',sep=' ')

array([23., 34., 67.])

In [7]:
import numpy as np
arr.dtype

dtype('int64')

In [6]:
import numpy as np
l=[1,2,3]
arr=np.array(l)
arr.dtype

dtype('int64')

In [2]:
import numpy as np
np.function(lambda i, j:i==j,(3,3))

AttributeError: module 'numpy' has no attribute 'function'

In [3]:
list(range(5))

[0, 1, 2, 3, 4]

In [4]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [6]:
(i*i for i in range(5))


<generator object <genexpr> at 0x7f816c4feb20>

In [7]:
np.fromiter(iterable,float)

NameError: name 'iterable' is not defined

In [8]:
np.fromstring('23 34 67',sep=' ')

array([23., 34., 67.])

In [11]:
np.fromstring('23, 34, 56',sep = ',')

array([23., 34., 56.])

In [12]:
list(range(5))

[0, 1, 2, 3, 4]

In [15]:
list(range(1.0,2.10)) #range cannot deal with float ...it is only for int (interview que)

TypeError: 'float' object cannot be interpreted as an integer

In [18]:
np.arange(0.1,10.2,0.2) #now we can execute 

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1])

In [24]:
np.linspace(1,5,20) # (start,end, range) (20 num in between 1 to 5)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [22]:
np.logspace(1,5,base=2)

array([ 2.        ,  2.11642982,  2.2396376 ,  2.37001791,  2.50798829,
        2.65399061,  2.80849244,  2.97198858,  3.14500263,  3.32808868,
        3.52183307,  3.72685628,  3.94381489,  4.17340372,  4.41635805,
        4.67345595,  4.94552078,  5.23342383,  5.53808714,  5.8604864 ,
        6.2016541 ,  6.56268285,  6.94472885,  7.34901563,  7.77683793,
        8.22956587,  8.70864932,  9.21562258,  9.75210923, 10.31982742,
       10.92059526, 11.55633675, 12.22908788, 12.94100316, 13.69436252,
       14.49157863, 15.3352046 , 16.22794219, 17.17265042, 18.17235475,
       19.23025679, 20.3497445 , 21.53440308, 22.78802646, 24.11462942,
       25.51846045, 27.00401538, 28.57605177, 30.23960411, 32.        ])

In [25]:
np.logspace(1,5,10,base=10) #we can change the log base

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros((3,4),int) #by default it is float if u want int mention it

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
arr3=np.zeros((3,4,5))

In [35]:
arr3.shape

(3, 4, 5)

In [37]:
arr3+5

array([[[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]]])

In [38]:
arr3*3

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])