In [8]:
import numpy as np
arr = np.ones((3,4))

In [12]:
arr+5 #add

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [13]:
arr*5 #multiplication

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [17]:
np.empty((3,4),int) #gives some random value 

array([[4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024],
       [4617315517961601024, 4617315517961601024, 4617315517961601024,
        4617315517961601024]])

In [19]:
np.eye(5)     #diagonal matrix #always gives 2d matrix so "one parameter"

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
np.eye(2,dtype=int) #to convert into int

array([[1, 0],
       [0, 1]])

In [28]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
#optional
import pandas as pd 
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [33]:
#extra topic
import random
random.choice((1,2,3,4,5,6))

2

In [34]:
random.choice('ajay')

'a'

In [36]:
random.randrange(1,1000)

232

In [37]:
random.randrange(1,1000,10)

751

In [38]:
random.random()

0.8257786777782108

In [40]:
lis=[1,2,3,4,5]
random.shuffle(lis)   #shuffle
lis

[4, 5, 1, 3, 2]

In [41]:
random.uniform(7,14) #a no. between 7 and 14

9.875142094164834

In [42]:
np.random.rand(2,3)

array([[0.17185543, 0.4423552 , 0.9980552 ],
       [0.73517285, 0.14183807, 0.18172231]])

In [43]:
np.random.rand(1)

array([0.0974396])

In [44]:
np.random.randn(2,3) #n means normal distribution

array([[-0.07540413, -1.16847995,  0.88373877],
       [ 0.26884188,  0.71633607, -1.82323187]])

In [46]:
np.random.random_sample() #instead in the form of an array here it is in num

0.3739635580542674

In [48]:
#half interval
# [0,1) now 0 is inclusive and 1 is exclusive

In [59]:
np.random.randint(1,5,size=(3,4)) #random int between 1 to 5 and size of 3 row and 4 coloumn

array([[3, 1, 4, 2],
       [2, 1, 2, 1],
       [4, 4, 4, 4]])

In [51]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [52]:
arr.size

12

In [53]:
arr.shape

(3, 4)

In [56]:
arr.ndim # means what is the dimention

2

In [58]:
arr.reshape(2,6) #2 row and 6 coloumn

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [60]:
arr.reshape(2,1) #array size is 12 here it is mul of 2 so it can't fit

ValueError: cannot reshape array of size 12 into shape (2,1)

In [61]:
arr.reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [62]:
arr.reshape(12,1)

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [63]:
arr.reshape(12,) #for 1d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
arr.reshape(4,-1)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
arr.reshape(4,-1000)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
arr.reshape(3,-100)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [68]:
arr.reshape(-1,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
arr.reshape(3,4).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
arr.reshape(12,1).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [2]:
import numpy as np
np.random.randint(1,10,(5,6))

array([[2, 5, 3, 6, 2, 8],
       [1, 4, 7, 3, 9, 9],
       [7, 9, 8, 1, 9, 1],
       [2, 2, 3, 9, 6, 6],
       [7, 6, 3, 7, 6, 4]])

In [4]:
arr>5

NameError: name 'arr' is not defined

In [8]:
import numpy as np
arr = np.ones((3,4))

In [11]:
arr[0] #to acess the element

array([1., 1., 1., 1.])

In [12]:
arr[1]

array([1., 1., 1., 1.])

In [13]:
arr[0][0]

1.0

In [14]:
arr[0,[1,3]]

array([1., 1.])

In [15]:
arr[2:4,[2,3]]

array([[1., 1.]])

NameError: name 'arr' is not defined

In [2]:
import numpy as np
arr = np.ones((3,4))

In [3]:
arr[2:5,[0,1]]

array([[1., 1.]])

In [4]:
arr[2:5,0:2] #slicing

array([[1., 1.]])

In [8]:
arr[[1,2]] #1 and 2 index

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
arr[1:2] #from 1 to 2

array([[1., 1., 1., 1.]])

In [10]:
arr[2:4,[1,3]] #2nd and 4th index but only specific that is from 1 to 3 column

array([[1., 1.]])

In [13]:
# to add arr1 + arr2
#arr1-arr2
#arr1* arr2

In [23]:
# for matrix multiplication 
#arr1 @arr 2
#arr1/ arr2 index wise divison

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [21]:
arr2 = np.array([[1, 2, 3, 4,
                 3,4,5,6]])
print(arr)

[1 2 3 4 5]


In [22]:
arr @ arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 5)

In [24]:
arr

array([1, 2, 3, 4, 5])

In [26]:
arr/0  #numpy understands infinity

/tmp/ipykernel_77/309187126.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0  #numpy understands infinity


array([inf, inf, inf, inf, inf])

In [28]:
#broad casting
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
arr+ 5 #5 added to each element this is broad casting

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [31]:
arr 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
a=np.array([1,2,3,4])
a


array([1, 2, 3, 4])

In [33]:
arr +a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [35]:
a.T # T is transpose

array([1, 2, 3, 4])

In [36]:
arr +a.T

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [38]:
a=np.array([1,2,3])
a.T

array([1, 2, 3])

In [40]:
arr2

array([[1, 2, 3, 4, 3, 4, 5, 6]])

In [46]:
np.sqrt(arr2) #for square root

array([[1.        , 1.41421356, 1.73205081, 2.        , 1.73205081,
        2.        , 2.23606798, 2.44948974]])

In [47]:
np.log10(arr2) #to find log

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.47712125,
        0.60205999, 0.69897   , 0.77815125]])

In [48]:
np.exp(arr2)  #to find exponential

array([[  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
         20.08553692,  54.59815003, 148.4131591 , 403.42879349]])

In [44]:
a

array([1, 2, 3])

In [49]:
np.min(a) # to find min value

1

In [50]:
np.max(arr2) #to find max value

6

In [52]:
arr2.T #TO transpose

array([[1],
       [2],
       [3],
       [4],
       [3],
       [4],
       [5],
       [6]])

In [54]:
arr2.flatten()  #reduce higher dim to 1d

array([1, 2, 3, 4, 3, 4, 5, 6])

In [58]:
#expand_dimention : expands array by inserting new axis

arr=np.array([[1,2,3],[4,5,6],[1,2,3]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [59]:
np.sum(arr)

27

In [61]:
np.sum(arr,axis=0)  #adding by column

array([ 6,  9, 12])

In [62]:
arr.ndim

2

In [64]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [65]:
arr.ndim

1

In [83]:
#expand_dimention : expands array by inserting new axis

arr1=np.expand_dims(arr,axis=0) #here dimentions expand by 1
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [84]:
arr1.ndim

3

In [85]:
arr2=np.expand_dims(arr1,axis=0)
arr2

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [86]:
arr2.shape

(1, 1, 3, 4)

In [87]:
arr1=np.expand_dims(arr,axis=1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [88]:
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
arr1=np.expand_dims(arr,axis=0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])