In [2]:
import numpy as np
data=np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [7]:
a=np.squeeze(data)  #reduce 1 dimention (it is the opposite of expand_dims)

In [10]:
a.ndim

AttributeError: 'function' object has no attribute 'ndim'

In [19]:
#repeat  # repeats the data but it flatttens (that is it repeat numbers by reducing it to 1d)
data

array([[1],
       [2],
       [3]])

In [20]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [21]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [22]:
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [24]:
np.repeat(a,2,axis=1) #axis=1 means column wise

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [2]:
import numpy as np
data=np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [3]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [6]:
np.diag(np.array([1,2,3,4]))  #element become diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [8]:
np.roll(data,1,axis=0)

array([[3],
       [1],
       [2]])

In [10]:
np.roll(data,1,axis=1)  #roll the coloumn

array([[1],
       [2],
       [3]])

In [11]:
#binary operation on array

In [12]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [13]:
arr1

array([[6, 6, 4, 6],
       [1, 8, 4, 8],
       [4, 6, 1, 4]])

In [14]:
arr2

array([[3, 8, 2, 5],
       [3, 3, 5, 6],
       [3, 8, 6, 6]])

In [15]:
arr1+arr2

array([[ 9, 14,  6, 11],
       [ 4, 11,  9, 14],
       [ 7, 14,  7, 10]])

In [16]:
arr1*arr2

array([[18, 48,  8, 30],
       [ 3, 24, 20, 48],
       [12, 48,  6, 24]])

In [17]:
arr1/arr2

array([[2.        , 0.75      , 2.        , 1.2       ],
       [0.33333333, 2.66666667, 0.8       , 1.33333333],
       [1.33333333, 0.75      , 0.16666667, 0.66666667]])

In [18]:
arr1-arr2

array([[ 3, -2,  2,  1],
       [-2,  5, -1,  2],
       [ 1, -2, -5, -2]])

In [19]:
arr1**arr2

array([[    216, 1679616,      16,    7776],
       [      1,     512,    1024,  262144],
       [     64, 1679616,       1,    4096]])

In [20]:
arr1>arr2

array([[ True, False,  True,  True],
       [False,  True, False,  True],
       [ True, False, False, False]])

In [21]:
-arr1

array([[-6, -6, -4, -6],
       [-1, -8, -4, -8],
       [-4, -6, -1, -4]])

In [3]:
#numpy string concepts
import numpy as np
arr=np.array(["pw","skills"])
arr

array(['pw', 'skills'], dtype='<U6')

In [4]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [6]:
np.char.upper(np.array(["ajay"]))

array(['AJAY'], dtype='<U4')

In [7]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [5]:
import numpy as np
arr=np.array(["pw","skills"])

np.char.title(arr)
arr

array(['pw', 'skills'], dtype='<U6')

In [6]:
data=np.array([[1],[2],[3]])
data

array([[1],
       [2],
       [3]])

In [14]:
#mathematical functions used in numpy 

In [15]:
np.sin(data)

array([[0.84147098],
       [0.90929743],
       [0.14112001]])

In [16]:
np.cos(data)

array([[ 0.54030231],
       [-0.41614684],
       [-0.9899925 ]])

In [17]:
np.tan(data)

array([[ 1.55740772],
       [-2.18503986],
       [-0.14254654]])

In [18]:
np.log10(data)

array([[0.        ],
       [0.30103   ],
       [0.47712125]])

In [19]:
np.exp(data)

array([[ 2.71828183],
       [ 7.3890561 ],
       [20.08553692]])

In [20]:
np.power(data,3)

array([[ 1],
       [ 8],
       [27]])

In [21]:
np.std(data)

0.816496580927726

In [22]:
np.mean(data)

2.0

In [23]:
np.var(data)

0.6666666666666666

In [24]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

np.subtract(arr1,arr2)

array([[ 2,  1, -2, -4],
       [ 3, -1,  0,  1],
       [-6,  1,  1, -3]])

In [25]:
np.multiply(arr1,arr2)

array([[63, 12, 63,  5],
       [54, 42,  4,  2],
       [ 7,  6, 72, 10]])

In [26]:
np.power(arr1,arr2)

array([[ 4782969,       64, 40353607,        1],
       [  531441,   279936,        4,        2],
       [       1,        9, 43046721,       32]])

In [27]:
np.sqrt(arr1)

array([[3.        , 2.        , 2.64575131, 1.        ],
       [3.        , 2.44948974, 1.41421356, 1.41421356],
       [1.        , 1.73205081, 3.        , 1.41421356]])

In [28]:
#sort and search 
arr=np.array([5,6,1,2])
arr

array([5, 6, 1, 2])

In [29]:
np.sort(arr)

array([1, 2, 5, 6])

In [32]:
np.searchsorted(arr,3)  #ans is 4 that means we have to insert at 3rd index

4

In [34]:
arr1=np.array([0,1,2,3,0,4]) #the numnebr of non zero is 4
np.count_nonzero(arr1)

4

In [35]:
arr1>0

array([False,  True,  True,  True, False,  True])

In [36]:
np.where(arr1 >0) #to know the index where it gives true or false value

(array([1, 2, 3, 5]),)

In [37]:
np.extract(arr1 >0,arr1)

array([1, 2, 3, 4])

In [38]:
arr1

array([0, 1, 2, 3, 0, 4])

In [39]:
arr1.byteswap() #to find how it stored in byte form

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808,                  0, 288230376151711744])

In [40]:
#matrix >> 2d array


In [43]:
import numpy.matlib as nm #matlib means matrix library

In [44]:
nm.zeros(5)


matrix([[0., 0., 0., 0., 0.]])

In [45]:
nm.ones((3,4)) #2d 

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [46]:
#numpy linear alebra

In [47]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))


In [48]:
arr1

array([[7, 8, 5, 9],
       [7, 4, 6, 3],
       [4, 5, 3, 6]])

In [49]:
arr2

array([[5, 5, 3, 9],
       [4, 8, 8, 1],
       [9, 5, 5, 7]])

In [50]:
arr1=np.array([[2,3],[4,5]])
arr2=np.array([[1,3],[4,5]])

In [51]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [56]:
# 7X+5Y-3Z=16
# 3X-5Y+2Z=-8
# 5X+3Y-7Z=0 
# a values consists of all LHS 
# b values consists of all RHS

In [52]:
a=np.array([[7,-5,-3],[3,-5,2],[5,3,-7]])
a

array([[ 7, -5, -3],
       [ 3, -5,  2],
       [ 5,  3, -7]])

In [53]:
b=np.array([16,-8,0])
b

array([16, -8,  0])

In [57]:
np.linalg.solve(a,b)   #solving the equations with linear algebra "linalg" is the function used

array([-15.11111111, -14.22222222, -16.88888889])

In [58]:
# to find  the determinant of a matrix
np.linalg.det(arr1)

-2.0

In [60]:
# to find the inverse of a matrix
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])

In [ ]:
############### NUMPY SERIS IS OVER  ;) ####################